const SHELVES=[['Classic Fiction','topic:fiction'],['Poetry & Drama','topic:poetry'],['Philosophy & Ideas','topic:philosophy'],['Indian Literature','Tagore Premchand'],['Adventure & Mystery','topic:mystery'],['Science & Discovery','topic:science']];
const PAGE_CHARS=1150;let dark=true, selected=null, reader=null;
const $=s=>document.querySelector(s), app=$('#app');
const author=b=>(b.authors||[]).map(a=>a.name).join(', ')||'Unknown author';
const cover=b=>b.formats?.['image/jpeg']||'';
async function searchBooks(q,n=24){const r=await fetch(`https://gutendex.com/books/?search=${encodeURIComponent(q)}`);if(!r.ok)throw Error('Search failed');return (await r.json()).results.slice(0,n)}
function strip(t){return t.replace(/[\s\S]*?\*\*\* START OF (?:THE|THIS) PROJECT GUTENBERG EBOOK[^\n]*\*\*\*/i,'').replace(/\*\*\* END OF (?:THE|THIS) PROJECT GUTENBERG EBOOK[\s\S]*/i,'').trim()}
async function textOf(b){for(const [type,url] of Object.entries(b.formats||{})){if(type.startsWith('text/plain')){const r=await fetch(url.replace('http://','https://'));if(r.ok){const t=await r.text();if(t.length>400)return strip(t)}}}throw Error('No readable plain-text edition is available for this title.')}
function pages(t){const out=[];let cur='';for(const p of t.replace(/\r\n/g,'\n').split(/\n\n+/)){if((cur+'\n\n'+p).length>PAGE_CHARS){if(cur)out.push(cur.trim());cur=p}else cur=cur?cur+'\n\n'+p:p}if(cur)out.push(cur.trim());return out}
function render(){document.documentElement.dataset.theme=dark?'dark':'light';app.innerHTML=`<div class="app"><header class="topbar"><div class="brand"><img class="brandLogo" src="src/assets/gyansetu-logo.svg" alt="GyanSetu logo"><div><b>GyanSetu</b><span>Free Digital Library</span></div></div><form class="search"><span>⌕</span><input id="q" placeholder="Search free books, authors, classics..."><button>Search</button></form><button class="iconBtn" id="theme">${dark?'☀':'☾'}</button></header><main><section class="hero"><div class="heroText"><div class="heroLogoWrap"><img class="heroLogo" src="src/assets/gyansetu-logo.svg" alt="GyanSetu"></div><p class="eyebrow">✦ public-domain learning, beautifully presented</p><h1>Read timeless books online with a Kindle-style library.</h1><p>Browse curated shelves, inspect book details, and open an animated page-flip reader designed for comfortable long-form reading.</p><div class="heroActions"><button data-search="classic literature">Explore classics</button><button class="ghost" data-search="Indian literature">Indian literature</button></div></div><div class="device"><div class="deviceTop">Library <span>All items</span></div><div class="gridMini" id="featured"></div></div></section><div id="content"></div></main></div>`;$('#theme').onclick=()=>{dark=!dark;render()};$('.search').onsubmit=e=>{e.preventDefault();showResults($('#q').value.trim()||'classic literature')};document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>showResults(b.dataset.search));loadFeatured();showShelves()}
function bookCard(b){return `<article class="bookCard"><button class="coverBtn" data-id="${b.id}">${cover(b)?`<img src="${cover(b)}" alt="${b.title.replaceAll('"','&quot;')}">`:`<span>${b.title}</span>`}<em>${Math.min(99,Math.max(1,Math.round((b.download_count||1000)/1300)))}%</em></button><h3>${b.title}</h3><p>${author(b)}</p><button class="read" data-id="${b.id}">ⓘ Details</button></article>`}
function bindBooks(books){document.querySelectorAll('[data-id]').forEach(el=>el.onclick=()=>openDetails(books.find(b=>String(b.id)===el.dataset.id)))}
async function loadFeatured(){const box=$('#featured');const books=(await Promise.all(['Pride and Prejudice','The Time Machine','Sherlock Holmes','Gitanjali'].map(q=>searchBooks(q,1).then(r=>r[0])))).filter(Boolean);box.innerHTML=books.map(b=>`<button data-id="${b.id}"><img src="${cover(b)}" alt=""><small>${Math.floor((b.download_count||1000)/1000)}k</small></button>`).join('');bindBooks(books)}
function showShelves(){const c=$('#content');c.innerHTML=SHELVES.map((s,i)=>`<section class="shelf"><div class="sectionHead"><h2>${s[0]}</h2><button>See all →</button></div><div class="rule"></div><div class="rail" id="rail${i}">${'<div class="skeleton"></div>'.repeat(6)}</div></section>`).join('');SHELVES.forEach(async(s,i)=>{try{const books=await searchBooks(s[1],12);$(`#rail${i}`).innerHTML=books.map(bookCard).join('');bindBooks(books)}catch{$(`#rail${i}`).innerHTML='<p class="muted">Could not load this shelf.</p>'}})}
async function showResults(q){const c=$('#content');c.innerHTML=`<section class="shelf"><div class="sectionHead"><h2>Results for “${q}”</h2></div><div class="rule"></div><div class="loader">◌ Searching shelves…</div></section>`;try{const books=await searchBooks(q,36);c.innerHTML=`<section class="shelf"><div class="sectionHead"><h2>Results for “${q}”</h2></div><div class="rule"></div><div class="results">${books.map(bookCard).join('')}</div></section>`;bindBooks(books)}catch{c.innerHTML='<p class="muted">Could not reach the index.</p>'}}
function openDetails(b){selected=b;document.body.insertAdjacentHTML('beforeend',`<div class="modal"><div class="details"><button class="close">×</button><div class="detailCover">${cover(b)?`<img src="${cover(b)}" alt="">`:''}</div><div><p class="eyebrow">★ Book details</p><h2>${b.title}</h2><p class="byline">${author(b)}</p><p class="desc">This public-domain edition is available through Project Gutenberg. Open it in GyanSetu's immersive reader to enjoy animated page turns, keyboard navigation, and a calm reading layout.</p><dl><dt>Subjects</dt><dd>${(b.subjects||[]).slice(0,4).join(' · ')||'Classic literature'}</dd><dt>Downloads</dt><dd>${(b.download_count||0).toLocaleString()}</dd></dl><button class="primary">📖 Start reading</button></div></div></div>`);$('.close').onclick=()=>$('.modal').remove();$('.primary').onclick=()=>{ $('.modal').remove(); openReader(b)}}
async function openReader(b){let page=0, ps=[];document.body.insertAdjacentHTML('beforeend',`<div class="reader"><div class="readerTop"><b>${b.title}</b><button id="rclose">×</button></div><div class="bookStage"><button id="prev">‹</button><div class="page"><div class="loader">◌ Opening the book…</div></div><button id="next">›</button></div></div>`);const close=()=>$('.reader')?.remove();$('#rclose').onclick=close;const paint=()=>{$('.page').innerHTML=`<p>${ps[page]}</p><span>${page+1} / ${ps.length}</span>`};const turn=d=>{if(!ps.length)return;const n=Math.max(0,Math.min(ps.length-1,page+d));if(n===page)return;$('.page').classList.add(d>0?'next':'prev');setTimeout(()=>{page=n;paint();$('.page').className='page'},360)};$('#next').onclick=()=>turn(1);$('#prev').onclick=()=>turn(-1);try{ps=pages(await textOf(b));paint()}catch(e){$('.page').innerHTML=`<p>${e.message}</p>`}window.onkeydown=e=>{if($('.reader')){if(e.key==='Escape')close();if(e.key==='ArrowRight')turn(1);if(e.key==='ArrowLeft')turn(-1)}}}
render();
